export const miniApi = {
  authLogin: '/mini/auth/login',
  authLogout: '/mini/auth/logout',
  overview: '/mini/overview',
  fields: '/mini/fields',
  fieldDetail: (id: string) => `/mini/fields/${id}`,
  devices: '/mini/devices',
  deviceDetail: (id: string) => `/mini/devices/${id}`,
  plans: '/mini/plans',
  planDetail: (id: string) => `/mini/plans/${id}`,
  planCreate: '/mini/plans',
  planStart: (id: string) => `/mini/plans/${id}/start`,
  planPause: (id: string) => `/mini/plans/${id}/pause`,
  planStop: (id: string) => `/mini/plans/${id}/stop`,
  strategies: '/mini/strategies',
  strategyDetail: (id: string) => `/mini/strategies/${id}`,
  strategyCreate: '/mini/strategies',
  strategyEnable: (id: string) => `/mini/strategies/${id}/enable`,
  strategyDisable: (id: string) => `/mini/strategies/${id}/disable`,
  strategyConfirm: (id: string) => `/mini/strategies/${id}/confirm`,
  strategyIgnore: (id: string) => `/mini/strategies/${id}/ignore`,
  me: '/mini/me',
  runtime: '/mini/runtime',
} as const;
